### ISSUE TITLE
gregg wants to know why slower diffusing morphogens win the majority

### ISSUE THREAD

**Issue by gszep** [gszep/reaction-diffusion#13]
We initialise differentially diffusing morphogens
![screenshot from 2018-01-29 10-16-43](https://user-images.githubusercontent.com/17977117/35506165-4e990832-04e0-11e8-99f3-5f70d6f0704a.png)
Blue diffuses twice as fast as yellow
![screenshot from 2018-01-29 10-16-54](https://user-images.githubusercontent.com/17977117/35506167-50762798-04e0-11e8-97e9-369b233e3bb6.png)
Yellow begins to gain ground, pushing back against blue
![screenshot from 2018-01-29 10-17-20](https://user-images.githubusercontent.com/17977117/35506171-525b4908-04e0-11e8-8e90-a98e0724096f.png)
We help blue by increasing its population, expecting a push back
![screenshot from 2018-01-29 10-17-30](https://user-images.githubusercontent.com/17977117/35506172-53d905ae-04e0-11e8-887a-16ece683ab71.png)
Only to find that yellow pushes back even harder
![screenshot from 2018-01-29 10-17-39](https://user-images.githubusercontent.com/17977117/35506174-55cae076-04e0-11e8-83cf-50b6bda618b5.png)
Eventually yellow dominates the whole plane
![screenshot from 2018-01-29 10-17-55](https://user-images.githubusercontent.com/17977117/35506177-57d163d6-04e0-11e8-80f9-897f8370c00f.png)

**Comment by csikasznagy** [comment]
The slower one will win, since locally that one will have higher concentration when the two fronts will meet.
